import { test, expect, state, scene, resume, elapsed } from './support'

test('title launches with Enter and the pause button works', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.getByRole('button', { name: 'LAUNCH SORTIE' })).toBeVisible()
  await page.waitForFunction(()=>window.__GAME_INSPECTOR__?.getState().ship.active==='strix')
  await page.screenshot({ path: info.outputPath('title.png') })
  await page.keyboard.press('Enter')
  await elapsed(page, 0.2)
  await page.getByRole('button', { name: 'Pause or resume' }).click()
  expect((await state(page)).paused).toBe(true)
  await page.getByRole('button', { name: 'RESUME FLIGHT' }).click()
  expect((await state(page)).paused).toBe(false)
})

test('real steering normalizes diagonals, respects bounds, and pauses time', async ({ page }) => {
  await scene(page, 'basic-flight'); await resume(page)
  await page.keyboard.down('KeyD'); await page.keyboard.down('KeyW')
  await elapsed(page, 0.2)
  const diagonal = await state(page)
  expect(Math.hypot(diagonal.player.velocity.x, diagonal.player.velocity.y)).toBeCloseTo(12, 5)
  await elapsed(page, 2)
  await page.keyboard.up('KeyD'); await page.keyboard.up('KeyW')
  expect((await state(page)).player.position.x).toBe(10)
  expect((await state(page)).player.position.y).toBe(5.5)
  await page.keyboard.press('Escape')
  const frozen = await state(page)
  // Wait for real render frames, not a wall-clock sleep, while checking simulation freeze.
  await page.evaluate(() => new Promise<void>(resolve => {
    let frames = 0; function tick() { if (++frames >= 15) resolve(); else requestAnimationFrame(tick) } tick()
  }))
  expect((await state(page)).missionElapsedTime).toBe(frozen.missionElapsedTime)
  await page.keyboard.press('Escape')
  await page.keyboard.down('ArrowLeft'); await page.keyboard.down('ArrowDown')
  await elapsed(page, frozen.missionElapsedTime + 3)
  await page.keyboard.up('ArrowLeft'); await page.keyboard.up('ArrowDown')
  expect((await state(page)).player.position.x).toBe(-10)
  expect((await state(page)).player.position.y).toBe(-5.5)
})

test('weapon fires visible projectiles, records cooldown, destroys enemy and scores', async ({ page }) => {
  await scene(page, 'basic-enemy'); await resume(page)
  await page.keyboard.down('Space')
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().playerProjectileCount > 0)
  const firing = await state(page)
  expect(firing.weaponCooldown).toBeGreaterThan(0)
  expect(firing.recentEvents.some(e => e.type === 'weapon-fired' && e.owner === 'player')).toBe(true)
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().recentEvents.some(e => e.type === 'enemy-hit'))
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().enemies.length === 0)
  await page.keyboard.up('Space')
  const final = await state(page)
  expect(final.score).toBe(100)
  expect(final.recentEvents.some(e => e.type === 'enemy-destroyed')).toBe(true)
  expect(final.recentCollisions.length).toBeGreaterThan(0)
})

test('aimed fire damages player, low shields fail, real R restarts', async ({ page }) => {
  await scene(page, 'enemy-fire'); await resume(page)
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().enemyProjectileCount > 0)
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().player.shields < 100)
  expect((await state(page)).recentEvents.some(e => e.type === 'player-hit')).toBe(true)
  await page.evaluate(() => window.__GAME_INSPECTOR__!.loadScene('low-health'))
  await resume(page)
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().status === 'game-over')
  expect((await state(page)).player.shields).toBe(0)
  await expect(page.getByRole('heading', { name: 'Out of the fight.' })).toBeVisible()
  await page.keyboard.press('KeyR')
  await elapsed(page, 0.1)
  const restarted = await state(page)
  expect(restarted.status).toBe('playing'); expect(restarted.player.shields).toBe(100)
  expect(restarted.score).toBe(0); expect(restarted.activeScene).toBe('mission-start')
  expect(restarted.recentEvents.some(e => e.type === 'game-restarted')).toBe(true)
})

test('low-health incoming shot is avoidable using keyboard', async ({ page }) => {
  await scene(page, 'low-health'); await resume(page)
  await page.keyboard.down('KeyD'); await elapsed(page, 0.5); await page.keyboard.up('KeyD')
  await elapsed(page, 2)
  expect((await state(page)).player.shields).toBe(10)
  expect((await state(page)).status).toBe('playing')
})

test('final encounter can be won with real fire, then restarted', async ({ page }) => {
  await scene(page, 'final-encounter'); await resume(page)
  await page.keyboard.down('Space')
  await page.waitForFunction(() => window.__GAME_INSPECTOR__!.getState().status === 'mission-complete', undefined, { timeout: 20_000 })
  await page.keyboard.up('Space')
  expect((await state(page)).score).toBeGreaterThanOrEqual(2000)
  expect((await state(page)).missionProgress).toBe(1)
  await expect(page.getByRole('heading', { name: 'The way is open.' })).toBeVisible()
  await page.keyboard.press('KeyR')
  expect((await state(page)).status).toBe('playing')
})
