import {test,expect,state,scene} from './support'

test('More is dismissible and utilities do not launch or resume flight',async({page},info)=>{
  await page.goto('/')
  await expect(page.getByRole('button',{name:'Feedback',exact:true})).toBeHidden()
  await expect(page.getByRole('button',{name:'Pause or resume'})).toBeHidden()
  await page.getByRole('button',{name:'More ⋯'}).click()
  await expect(page.getByRole('button',{name:'More ⋯'})).toHaveAttribute('aria-expanded','true')
  await expect(page.locator('[data-utilities] [data-board]')).toBeHidden()
  await page.screenshot({path:info.outputPath('main-more.png')})
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button',{name:'More ⋯'})).toBeFocused()
  await expect(page.getByRole('button',{name:'More ⋯'})).toHaveAttribute('aria-expanded','false')
  expect((await state(page)).status).toBe('title')
  await page.getByRole('button',{name:'More ⋯'}).click()
  await page.getByRole('button',{name:'Audio',exact:true}).click()
  await expect(page.getByRole('slider',{name:'Music volume'})).toBeVisible()
  await page.getByRole('button',{name:'Close audio'}).click()
  await page.getByRole('button',{name:'LAUNCH SORTIE'}).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button',{name:'More ⋯'}).click()
  await page.getByRole('button',{name:'Leaderboard',exact:true}).click()
  await page.getByRole('button',{name:'Close leaderboard'}).click()
  expect((await state(page)).paused).toBe(true)
  await page.getByRole('button',{name:'RESUME FLIGHT'}).click()
  expect((await state(page)).paused).toBe(false)
})

test('results put leaderboard and feedback in More',async({page},info)=>{
  await scene(page,'mission-complete')
  await expect(page.getByRole('button',{name:'Leaderboard',exact:true})).toBeHidden()
  await expect(page.getByRole('button',{name:'Feedback',exact:true})).toBeHidden()
  await expect(page.getByRole('button',{name:'Main Menu',exact:true})).toBeVisible()
  await page.screenshot({path:info.outputPath('results.png')})
  await page.getByRole('button',{name:'More ⋯'}).click()
  await page.getByRole('button',{name:'Feedback',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'Send feedback'})).toBeVisible()
})

test('landscape phone More fits, dismisses outside, and exposes feedback',async({page},info)=>{
  await page.setViewportSize({width:844,height:390})
  await page.goto('/')
  await page.getByRole('button',{name:'More ⋯'}).click()
  const box=await page.locator('[data-utilities]').boundingBox()
  expect(box!.x+box!.width).toBeLessThanOrEqual(844)
  expect(box!.y+box!.height).toBeLessThanOrEqual(390)
  await page.screenshot({path:info.outputPath('mobile-more.png')})
  await page.locator('.brand').click({force:true})
  await expect(page.locator('[data-utilities]')).toBeHidden()
})
